### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by DamianDib9** [Jawad-Nazari/Awesome_book_with_ES6#2]
### **Good Job!**
________________________________________
![image](https://thumbs.gfycat.com/IlliterateForthrightDunlin-max-1mb.gif)

**Highlights:**
✔️ Following GitHub Flow
✔️ Following requirements

Keep on that track.

Happy coding! 💃

**Comment by Jawad-Nazari** [comment]
Hi @DamianDib9 ,

Thanks for your nice comment. I'm going to close it now.
